 ## Task #1

In [12]:
import numpy as np

# Generate random temperature values between -10 and 40 degrees Celsius
temperature_data = np.random.uniform(-10, 40, (500, 365))
# Generate random humidity values between 0 and 100 percent
humidity_data = np.random.randint(0, 101, (500, 365))

print("Temperature Data:\n", temperature_data)
print("Humidity Data:\n", humidity_data)


Temperature Data:
 [[ 2.12780771e+01  3.66862810e+01  2.07415609e+01 ...  2.32634543e+01
   1.34342581e+01 -3.17716438e+00]
 [-8.99023798e+00  3.59132112e+00  1.46619784e+01 ...  2.89112157e+01
  -1.62432171e+00 -6.09090678e+00]
 [ 3.75674449e+01  3.46528797e+01  3.28211540e+01 ...  1.18474966e+01
  -9.90680939e+00  3.57512446e+01]
 ...
 [ 2.34539412e+01  1.00849923e+01 -2.39127845e+00 ...  3.57068138e+01
   8.34867616e+00  3.36058494e+01]
 [ 3.25125039e+01  3.60413613e+01 -1.78140847e-01 ...  4.17385360e+00
   1.45257082e+01 -8.25786608e+00]
 [-1.72132194e+00 -7.64115461e-03  2.32494866e+01 ...  3.36524006e+01
   3.24741328e+01  3.94495130e+01]]
Humidity Data:
 [[ 98  13  32 ...  33  59  69]
 [ 64  16  39 ...  37  87  17]
 [ 49  81  45 ...  27  89  61]
 ...
 [ 93  45  57 ... 100  67  40]
 [ 94  47  66 ...  27  60  53]
 [ 32  53  50 ...  43  76  82]]


## Task #2

In [19]:
import numpy as np

# Function to introduce NaN values in a dataset
def introduce_missing_data(data, percentage=0.05):
    # Ensure the data type is float to allow NaN values
    data = data.astype(float)  # Convert to float
    total_values = data.size
    num_missing = int(total_values * percentage)
    missing_indices = np.random.choice(total_values, num_missing, replace=False)
    # Set the selected indices in the original data to NaN
    data.flat[missing_indices] = np.nan  
    return np.count_nonzero(np.isnan(data))  # Count NaN values


temperature_data = np.random.randint(low=-10, high=40, size=(500, 365)).astype(float)
humidity_data = np.random.randint(low=0, high=101, size=(500, 365)).astype(float)

missing_temperature = introduce_missing_data(temperature_data)
missing_humidity = introduce_missing_data(humidity_data)

# Print the number of missing entries
print(f"Missing temperature entries: {missing_temperature}")
print(f"Missing humidity entries: {missing_humidity}")


Missing temperature entries: 9125
Missing humidity entries: 9125


## Task#3

In [22]:
temperature_data_fahrenheit = temperature_data * 9/5 + 32

#Hypothetiacl Formula
discomfort_index = temperature_data_fahrenheit + (humidity_data / 100) * 20 
discomfort_index[discomfort_index > 80] = 80  # Cap values at 80

print("Discomfort Index:\n", discomfort_index)


Discomfort Index:
 [[44.8 63.2 80.  ... 26.4 33.4 64.8]
 [80.  42.  47.8 ... 55.6 74.4 46.8]
 [80.  22.4 68.2 ... 34.2 67.6 53.6]
 ...
 [58.8 77.6 80.  ... 37.2 62.4 17.2]
 [79.4 58.6 19.  ... 76.8 58.4 54.4]
 [80.  75.8 62.2 ... 80.  21.4 80. ]]


## Task#4

In [27]:
january_temperatures = temperature_data[:, :31]

# Calculate the average January temperature across all locations
average_january_temp = np.nanmean(january_temperatures)
print(f"Average January Temperature: {average_january_temp:.2f}")


Average January Temperature: 14.61


## Task#5

In [30]:
# Mark temperatures above 35°C as NaN
extreme_temp_mask = temperature_data > 35
temperature_data[extreme_temp_mask] = np.nan

# Count null values per location
null_counts = np.count_nonzero(np.isnan(temperature_data), axis=1)
print(f"Number of null values per location: {null_counts}")


Number of null values per location: [23 26 32 25 24 19 37 30 38 36 35 18 28 35 18 20 37 26 22 40 26 28 22 34
 24 31 23 30 25 41 29 31 32 35 25 32 32 26 28 25 22 25 36 37 31 35 30 28
 25 30 28 28 32 41 34 32 31 28 26 27 31 27 32 23 24 37 32 34 26 25 33 20
 34 32 22 34 35 24 31 37 32 31 37 28 19 33 23 26 28 24 36 36 33 28 24 34
 27 33 35 23 30 29 27 38 36 30 30 33 31 28 31 27 33 26 31 38 35 23 28 19
 26 30 28 23 30 22 38 26 34 29 32 27 34 28 28 33 32 26 31 32 25 28 33 31
 17 29 33 26 24 36 35 30 35 31 26 23 30 27 27 23 34 27 38 24 34 26 28 30
 30 28 29 32 33 27 35 29 24 28 30 24 25 19 23 30 35 33 32 29 23 33 32 32
 33 26 22 26 20 31 24 27 31 26 34 39 27 27 30 29 31 31 30 32 38 26 30 36
 32 28 25 24 35 27 30 30 35 36 30 23 29 38 34 38 33 30 29 33 29 26 32 30
 41 31 26 29 26 29 33 30 29 22 26 27 34 21 33 34 24 30 23 26 29 25 26 20
 29 24 25 34 34 25 35 31 24 28 29 26 24 34 24 31 30 37 30 24 27 21 27 22
 19 23 23 38 35 33 24 30 32 28 27 28 21 33 32 27 33 32 33 29 37 23 25 37
 25 19 29 28 24

## Task#6

In [37]:
# Reshape to quarters (4 quarters of 91 days each, last quarter may have 92)
quarters = temperature_data.reshape(500, 4, 91)  # Assuming the last quarter takes the remainder
quarterly_avg_temp = np.nanmean(quarters, axis=1)  # Average across the quarters
print("Quarterly Average Temperatures:\n", quarterly_avg_temp)


ValueError: cannot reshape array of size 182500 into shape (500,4,91)

## Task#7

In [41]:
# Classify humidity levels
dry_days = (humidity_data < 30).sum(axis=1)
humid_days = (humidity_data > 70).sum(axis=1)

print(f"Total Dry Days per Location: {dry_days}")
print(f"Total Humid Days per Location: {humid_days}")


Total Dry Days per Location: [104  92 106 101 102 116 104 113 112 116 110 114 123 114 107  98 110 117
 102 101  98 128 109 120 105 100 107 109  95  87 106 106 112 115 109 101
 112 118  97 120 110 111 110 112 111  91 109 112 111 108 114 116 124 107
 105  99 105 117 107 103 104 117 107 106 107 110 116 116 119 104 123  99
 105 101 118  98 115 115 110 112 124 110  96  98 108 112 109 120 115 118
 114 115 111 116 115 119  98 102  94 101 101  98 103 110 103 113 118 127
 110  97 118 117 108 113 117 108 102 109 110  92 101 115 104 116  99 100
 114 105 109 107 111 111 114 106  93 104 124 111  92 112 123 109 111 113
 105 109 105 112  80 104 107  94  97  99  96 105 138 102 110  98 101 102
 105 104 112 106 101  94 104 108 122 114 106 102 102  99 111 108 108 110
 111 122 107 102 112 105 108 111 100 102  96 117 104 111 104 106 122  92
 112 125 108 109 104  97 107 118 108 127 115 115 106 109 111  97 123 106
 119 109 124 100 109 111 108 110 113 105 102 103 100 100 107 115 107 119
 115 103 118 104 107 1

## Task#8

In [44]:
pressure_trend = np.random.normal(loc=0, scale=2, size=(365))  # Random pressure trend

# Adjust temperature based on pressure trend (simple adjustment)
adjusted_temperature_data = temperature_data + pressure_trend.reshape(1, 365)  # Broadcast the trend
print("Adjusted Temperature Data:\n", adjusted_temperature_data)


Adjusted Temperature Data:
 [[ -1.1012767   13.09728186  27.55511878 ... -11.09544279  -0.5693017
   10.98865094]
 [ 28.8987233    4.09728186   2.55511878 ...   2.90455721  15.4306983
    2.98865094]
 [ 20.8987233   -4.90271814  20.55511878 ...  -1.09544279  13.4306983
    1.98865094]
 ...
 [ 11.8987233   18.09728186  33.55511878 ...  -8.09544279  11.4306983
   -9.01134906]
 [ 13.8987233   10.09728186  -8.44488122 ...  16.90455721  14.4306983
    9.98865094]
 [         nan  21.09728186  14.55511878 ...          nan  -8.5693017
           nan]]
